{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guestbook.fullname" . }}-secret
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secret.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
